// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.12.2
// source: proto/islb/islb.proto

package islb

import (
	ion "github.com/pion/ion/proto/ion"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid     string `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Nid     string `protobuf:"bytes,2,opt,name=nid,proto3" json:"nid,omitempty"`
	Service string `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *FindNodeRequest) Reset() {
	*x = FindNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_islb_islb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNodeRequest) ProtoMessage() {}

func (x *FindNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_islb_islb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNodeRequest.ProtoReflect.Descriptor instead.
func (*FindNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_islb_islb_proto_rawDescGZIP(), []int{0}
}

func (x *FindNodeRequest) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *FindNodeRequest) GetNid() string {
	if x != nil {
		return x.Nid
	}
	return ""
}

func (x *FindNodeRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type FindNodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*ion.Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *FindNodeReply) Reset() {
	*x = FindNodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_islb_islb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindNodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNodeReply) ProtoMessage() {}

func (x *FindNodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_islb_islb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNodeReply.ProtoReflect.Descriptor instead.
func (*FindNodeReply) Descriptor() ([]byte, []int) {
	return file_proto_islb_islb_proto_rawDescGZIP(), []int{1}
}

func (x *FindNodeReply) GetNodes() []*ion.Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nid string `protobuf:"bytes,1,opt,name=nid,proto3" json:"nid,omitempty"`
	Sid string `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_islb_islb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_islb_islb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_islb_islb_proto_rawDescGZIP(), []int{2}
}

func (x *WatchRequest) GetNid() string {
	if x != nil {
		return x.Nid
	}
	return ""
}

func (x *WatchRequest) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

type ISLBEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*ISLBEvent_Session
	//	*ISLBEvent_Stream
	Payload isISLBEvent_Payload `protobuf_oneof:"payload"`
}

func (x *ISLBEvent) Reset() {
	*x = ISLBEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_islb_islb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ISLBEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ISLBEvent) ProtoMessage() {}

func (x *ISLBEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_islb_islb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ISLBEvent.ProtoReflect.Descriptor instead.
func (*ISLBEvent) Descriptor() ([]byte, []int) {
	return file_proto_islb_islb_proto_rawDescGZIP(), []int{3}
}

func (m *ISLBEvent) GetPayload() isISLBEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ISLBEvent) GetSession() *ion.SessionEvent {
	if x, ok := x.GetPayload().(*ISLBEvent_Session); ok {
		return x.Session
	}
	return nil
}

func (x *ISLBEvent) GetStream() *ion.StreamEvent {
	if x, ok := x.GetPayload().(*ISLBEvent_Stream); ok {
		return x.Stream
	}
	return nil
}

type isISLBEvent_Payload interface {
	isISLBEvent_Payload()
}

type ISLBEvent_Session struct {
	Session *ion.SessionEvent `protobuf:"bytes,1,opt,name=session,proto3,oneof"`
}

type ISLBEvent_Stream struct {
	Stream *ion.StreamEvent `protobuf:"bytes,2,opt,name=stream,proto3,oneof"`
}

func (*ISLBEvent_Session) isISLBEvent_Payload() {}

func (*ISLBEvent_Stream) isISLBEvent_Payload() {}

var File_proto_islb_islb_proto protoreflect.FileDescriptor

var file_proto_islb_islb_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x73, 0x6c, 0x62, 0x2f, 0x69, 0x73, 0x6c,
	0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x69, 0x73, 0x6c, 0x62, 0x1a, 0x13, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6f, 0x6e, 0x2f, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x22, 0x30, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x1f, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x69, 0x6f, 0x6e, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x32, 0x0a, 0x0c, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6e, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x22, 0x71, 0x0a, 0x09, 0x49, 0x53, 0x4c,
	0x42, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x07, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0x73, 0x0a, 0x04,
	0x49, 0x53, 0x4c, 0x42, 0x12, 0x2e, 0x0a, 0x0d, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x53, 0x4c, 0x42,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0f, 0x2e, 0x69, 0x73, 0x6c, 0x62, 0x2e, 0x49, 0x53, 0x4c,
	0x42, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x0a, 0x2e, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x49, 0x53, 0x4c,
	0x42, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x69, 0x73, 0x6c, 0x62, 0x2e, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x69, 0x73, 0x6c,
	0x62, 0x2e, 0x49, 0x53, 0x4c, 0x42, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x69, 0x6f, 0x6e, 0x2f, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69,
	0x73, 0x6c, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_islb_islb_proto_rawDescOnce sync.Once
	file_proto_islb_islb_proto_rawDescData = file_proto_islb_islb_proto_rawDesc
)

func file_proto_islb_islb_proto_rawDescGZIP() []byte {
	file_proto_islb_islb_proto_rawDescOnce.Do(func() {
		file_proto_islb_islb_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_islb_islb_proto_rawDescData)
	})
	return file_proto_islb_islb_proto_rawDescData
}

var file_proto_islb_islb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_islb_islb_proto_goTypes = []interface{}{
	(*FindNodeRequest)(nil),  // 0: islb.FindNodeRequest
	(*FindNodeReply)(nil),    // 1: islb.FindNodeReply
	(*WatchRequest)(nil),     // 2: islb.WatchRequest
	(*ISLBEvent)(nil),        // 3: islb.ISLBEvent
	(*ion.Node)(nil),         // 4: ion.Node
	(*ion.SessionEvent)(nil), // 5: ion.SessionEvent
	(*ion.StreamEvent)(nil),  // 6: ion.StreamEvent
	(*ion.Empty)(nil),        // 7: ion.Empty
}
var file_proto_islb_islb_proto_depIdxs = []int32{
	4, // 0: islb.FindNodeReply.nodes:type_name -> ion.Node
	5, // 1: islb.ISLBEvent.session:type_name -> ion.SessionEvent
	6, // 2: islb.ISLBEvent.stream:type_name -> ion.StreamEvent
	3, // 3: islb.ISLB.PostISLBEvent:input_type -> islb.ISLBEvent
	2, // 4: islb.ISLB.WatchISLBEvent:input_type -> islb.WatchRequest
	7, // 5: islb.ISLB.PostISLBEvent:output_type -> ion.Empty
	3, // 6: islb.ISLB.WatchISLBEvent:output_type -> islb.ISLBEvent
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_islb_islb_proto_init() }
func file_proto_islb_islb_proto_init() {
	if File_proto_islb_islb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_islb_islb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_islb_islb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindNodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_islb_islb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_islb_islb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ISLBEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_islb_islb_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ISLBEvent_Session)(nil),
		(*ISLBEvent_Stream)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_islb_islb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_islb_islb_proto_goTypes,
		DependencyIndexes: file_proto_islb_islb_proto_depIdxs,
		MessageInfos:      file_proto_islb_islb_proto_msgTypes,
	}.Build()
	File_proto_islb_islb_proto = out.File
	file_proto_islb_islb_proto_rawDesc = nil
	file_proto_islb_islb_proto_goTypes = nil
	file_proto_islb_islb_proto_depIdxs = nil
}
