// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: protos/avp.proto

package avp

import (
	proto "github.com/golang/protobuf/proto"
	ion "github.com/pion/ion/pkg/grpc/ion"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Element struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Element Name
	// webmsaver/mixer/opencv/play/record/ml
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// params for element.
	Parameters []*ion.Parameter `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
}

func (x *Element) Reset() {
	*x = Element{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_avp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element) ProtoMessage() {}

func (x *Element) ProtoReflect() protoreflect.Message {
	mi := &file_protos_avp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) {
	return file_protos_avp_proto_rawDescGZIP(), []int{0}
}

func (x *Element) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Element) GetParameters() []*ion.Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type AVPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//media source
	//node id, sfu-01
	Nid string `protobuf:"bytes,1,opt,name=nid,proto3" json:"nid,omitempty"`
	//session id, room1
	Sid string `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	//choose streams to send to the AVP node.
	//streams = [${msid}:[ {id: ${trackId}, kind:audio}, {id: ${trackId}, kind:video}]
	Streams []*ion.Stream `protobuf:"bytes,3,rep,name=streams,proto3" json:"streams,omitempty"`
	//choose process elements
	Elements []*Element `protobuf:"bytes,4,rep,name=elements,proto3" json:"elements,omitempty"`
}

func (x *AVPRequest) Reset() {
	*x = AVPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_avp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AVPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AVPRequest) ProtoMessage() {}

func (x *AVPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_avp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AVPRequest.ProtoReflect.Descriptor instead.
func (*AVPRequest) Descriptor() ([]byte, []int) {
	return file_protos_avp_proto_rawDescGZIP(), []int{1}
}

func (x *AVPRequest) GetNid() string {
	if x != nil {
		return x.Nid
	}
	return ""
}

func (x *AVPRequest) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *AVPRequest) GetStreams() []*ion.Stream {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *AVPRequest) GetElements() []*Element {
	if x != nil {
		return x.Elements
	}
	return nil
}

type AVPReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AVPReply) Reset() {
	*x = AVPReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_avp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AVPReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AVPReply) ProtoMessage() {}

func (x *AVPReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_avp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AVPReply.ProtoReflect.Descriptor instead.
func (*AVPReply) Descriptor() ([]byte, []int) {
	return file_protos_avp_proto_rawDescGZIP(), []int{2}
}

func (x *AVPReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AVPReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_protos_avp_proto protoreflect.FileDescriptor

var file_protos_avp_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x76, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x76, 0x70, 0x1a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x07, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69,
	0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x0a, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0x81, 0x01, 0x0a, 0x0a, 0x41, 0x56, 0x50,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x07, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x69,
	0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x07, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x73, 0x12, 0x28, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x76, 0x70, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x3a, 0x0a, 0x08,
	0x41, 0x56, 0x50, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x30, 0x0a, 0x03, 0x41, 0x56, 0x50, 0x12,
	0x29, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x0f, 0x2e, 0x61, 0x76, 0x70,
	0x2e, 0x41, 0x56, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x61, 0x76,
	0x70, 0x2e, 0x41, 0x56, 0x50, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x6f, 0x6e, 0x2f, 0x69, 0x6f,
	0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x76, 0x70, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_avp_proto_rawDescOnce sync.Once
	file_protos_avp_proto_rawDescData = file_protos_avp_proto_rawDesc
)

func file_protos_avp_proto_rawDescGZIP() []byte {
	file_protos_avp_proto_rawDescOnce.Do(func() {
		file_protos_avp_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_avp_proto_rawDescData)
	})
	return file_protos_avp_proto_rawDescData
}

var file_protos_avp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_avp_proto_goTypes = []interface{}{
	(*Element)(nil),       // 0: avp.Element
	(*AVPRequest)(nil),    // 1: avp.AVPRequest
	(*AVPReply)(nil),      // 2: avp.AVPReply
	(*ion.Parameter)(nil), // 3: ion.Parameter
	(*ion.Stream)(nil),    // 4: ion.Stream
}
var file_protos_avp_proto_depIdxs = []int32{
	3, // 0: avp.Element.parameters:type_name -> ion.Parameter
	4, // 1: avp.AVPRequest.streams:type_name -> ion.Stream
	0, // 2: avp.AVPRequest.elements:type_name -> avp.Element
	1, // 3: avp.AVP.Process:input_type -> avp.AVPRequest
	2, // 4: avp.AVP.Process:output_type -> avp.AVPReply
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_avp_proto_init() }
func file_protos_avp_proto_init() {
	if File_protos_avp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_avp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Element); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_avp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AVPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_avp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AVPReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_avp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_avp_proto_goTypes,
		DependencyIndexes: file_protos_avp_proto_depIdxs,
		MessageInfos:      file_protos_avp_proto_msgTypes,
	}.Build()
	File_protos_avp_proto = out.File
	file_protos_avp_proto_rawDesc = nil
	file_protos_avp_proto_goTypes = nil
	file_protos_avp_proto_depIdxs = nil
}
